### ISSUE TITLE
Install failed with "ImportError: PyQt4 classes cannot be imported in QGIS 3.x. Use PyQt5 or the version independent qgis.PyQt import instead. "

### ISSUE THREAD

**Issue by XRolland** [Oslandia/landsurveycodesimport#16]
Hi,

I just tried to setup your plugin in QGIS 3.10.4 on Ubuntu 18.04. Set up failed with this message :

```
Impossible de charger l'extension 'LandSurveyCodesImport' provoque une erreur lors de l'appel à sa méthode classFactory()

ImportError: PyQt4 classes cannot be imported in QGIS 3.x. Use PyQt5 or the version independent qgis.PyQt import instead. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LandSurveyCodesImport/__init__.py", line 33, in classFactory
    from .land_survey_field_codes import LandSurveyFieldCodes
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LandSurveyCodesImport/land_survey_field_codes.py", line 30, in 
    from .land_survey_field_codes_dialog import LandSurveyFieldCodesDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LandSurveyCodesImport/land_survey_field_codes_dialog.py", line 41, in 
    resource_suffix='')
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 201, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 242, in 
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/resources.py", line 10, in 
    from PyQt4 import QtCore
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 742, in _import
    raise ImportError(msg)
ImportError: PyQt4 classes cannot be imported in QGIS 3.x.
Use PyQt5 or the version independent qgis.PyQt import instead.`

Version de Python : 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0] 
Version de QGIS : 3.10.4-A Coruña A Coruña, exporte

Chemin Python :
/usr/share/qgis/python
/home/USER/.local/share/QGIS/QGIS3/profiles/default/python
/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/USER/.local/share/QGIS/QGIS3/profiles/default/python
/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary
/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs
/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools
```
I hope to be able to try your plugin soon, as I used a Trimble M3 station with JobXML file for many years... 

Regards,
Xavier

**Comment by lbartoletti** [comment]
The error seems to be from go2mapillary extension

>   File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/resources.py", line 10, in 
    from PyQt4 import QtCore

Can you try to disable it, please?

**Comment by XRolland** [comment]
Hi,
I removed it, re-install **landsurveycodesimport** without any problem, and finally re-install **go2mapillary** without problem neither warning. 
Everything was working (didn't execute the codification but windows opened without problem). But when I closed QGIS and relaunched it, I got the same warning again. 
So I disabled one again **go2mapillary**, re-install for more safety **landsurveycodesimport** (without warning window) and closed QGIS.
When I ran QGIS one more time, I got neither no warning window, but just in the log panel, in the Python warning part: 

```
2020-04-09T22:41:56     WARNING    warning:/usr/lib/python3/dist-packages/PyQt5/uic/objcreator.py:152: DeprecationWarning: 'U' mode is deprecated
              plugin = open(filename, 'rU')
             
             traceback: File "", line 1, in 
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 354, in startPlugin
              if not _startPlugin(packageName):
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LandSurveyCodesImport/__init__.py", line 33, in classFactory
              from .land_survey_field_codes import LandSurveyFieldCodes
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LandSurveyCodesImport/land_survey_field_codes.py", line 30, in 
              from .land_survey_field_codes_dialog import LandSurveyFieldCodesDialog
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LandSurveyCodesImport/land_survey_field_codes_dialog.py", line 41, in 
              resource_suffix='')
              File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 198, in loadUiType
              winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix, import_from)
              File "/usr/lib/python3/dist-packages/PyQt5/uic/Compiler/compiler.py", line 53, in __init__
              qtproxies.QtWidgets, CompilerCreatorPolicy())
              File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 177, in __init__
              self.factory = QObjectCreator(creatorPolicy)
              File "/usr/lib/python3/dist-packages/PyQt5/uic/objcreator.py", line 85, in __init__
              if self.load_plugin(filename, plugin_globals, plugin_locals):
              File "/usr/lib/python3/dist-packages/PyQt5/uic/objcreator.py", line 152, in load_plugin
              plugin = open(filename, 'rU')
```
I have no idea if it's related... 

Do you understand what's the conflict between the two plugins?

**Comment by delhomer** [comment]
The project is being migrated; the thread is living at https://gitlab.com/Oslandia/qgis/landsurveycodesimport/-/issues/16.
